#!/usr/bin/env bash

export DATA_PATH="data/"
export COMP_BENCH="./"

excludes="--exclude data/ --exclude publications/ --exclude mpx.* --exclude build/ --exclude tmp/ --exclude raw_results/"
ssh_flags=""

# select a server
if [ $1 == 'a' ]; then
    server='alienware'
elif [ $1 == 'm' ]; then
    server='work_main'
    ssh_flags="-t"
elif [ $1 == 's1' ]; then
    server='sereca'
elif [ $1 == 's2' ]; then
    server='sereca2'
elif [ $1 == 's3' ]; then
    server='sereca3'
else
    echo "Unknown server"
    exit 1
fi

# define commands
if [ $2 == 's' ]; then
    echo "Deploying to the $server"
    rsync -ua ${excludes} . ${server}:fex/
elif [ $2 == 'c' ]; then
    echo "Deploying to the $server container"
    rsync -ua ${excludes}  ./* ${server}:fex/data_fex/up/
    ssh ${ssh_flags} ${server} "sudo docker exec cb_fex /bin/bash -c \"rsync -ua /data/up/ ./\""
elif [ $2 == 'a' ]; then
    echo "Deploying to the $server container - asm"
    rsync -ua ./asm_measurements/* ${server}:fex/data_fex/up/asm/
    ssh ${ssh_flags} ${server} "sudo docker exec cb_fex /bin/bash -c \"rsync -ua /data/up/asm/ ./asm_test/\""
elif [ $2 == 'r' ]; then
    echo "Getting results from the $server container"
    rsync -a  ${server}:fex/data_fex/results/ ./data/results/
else
    echo "Doing nothing"
fi


# local container
if [ $1 == 'l' ]; then
    if [ $2 == 's' ]; then
        echo "Deploying to the local dir"
        rsync -ar ${excludes} . ~/experiments/
    elif [ $2 == 'c' ]; then
        echo "Deploying to the local container"
        rsync -ua ${excludes} . ~/experiments/data_fex/up/
        sudo docker exec cb_fex /bin/bash -c " rsync -ua --exclude parallel* --exclude publications/* /data/up/ ./ "
    elif [ $2 == 'r' ]; then
        echo "Getting results from the local container"
        rsync -ua  ~/experiments/data_fex/results/ ./data/results/
    fi

fi
