name: Test

on:
  push:
  schedule:
    - cron:  '23 4 * * 4' # Run tests each week

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      # Bash tests
      - name: Bash tests
        run: |
          fex2/tests/run_bash_tests.sh

      # Python tests
      - name: Set up perf
        run: sudo sysctl -w kernel.perf_event_paranoid=-1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -e .
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with unittest
        run: python -m unittest

      # Finish
      - name: Set permissions for upload
        if: ${{ always() }}
        run: sudo chown -R $USER /tmp/fex2_test_*/
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-result
          path: |
            /tmp/fex2_test_*/**/*.log
            /tmp/fex2_test_*/**/*.csv
            /tmp/fex2_test_*/**/*.pdf
